---
- hosts: localhost-py3
  become: true

  tasks:

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - git

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce=18.06.2~ce~3-0~ubuntu
      - containerd.io
    notify:
      - docker status

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      group: docker

  - name: Install python and its dependencies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3 
      - python3-pip

  - name: Install pipenv
    command: pip3 install pipenv docker

  - name:
    git:
      repo: https://github.com/erickcezar/minio-uploader.git
      dest: /home/ubuntu/minio-uploader
    become_user: ubuntu  

  - name: pipenv deploy
    command: chdir=/home/ubuntu/minio-uploader pipenv --python 3 install --system --deploy

  handlers:
  - name: docker status
    service: name=docker state=started
